const CardData =[ 
{
    id: 1,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    img: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320" ,
    llojiPaisjes: "Lloji i pajisjes:",
    paisja: "SMARTWATCH",
    sistemiOperativ: "Sisteme operative te pajtueshme:",
    sensori: "Sensori i rrahjeve te zemres:",
    sensoriInfo: "po",
    bateri: "Jetegjatesia e baterise:",
    bateriinfo: "288 ore",
    stars: "⭐⭐⭐⭐⭐",
    paragraphStars: "32",
    cmimiRekomandim: "E rekomanduar 39.99 €",
    cmimi: "34,99 €",
    link: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    kontributi: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    opsionetDorezimi: "Opsionet e dorezimit",
    opsionetDorezimi2: "+2,99 €",
    opsionetDorezimi3: " Dorezimi i parashikuar 21.08.2024 - 23.08.2024 (Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    koleksioni: "Koleksioni FALAS ne dyqan",
    kontrollKolkesioni: "Kontrolloni koleksionin ne dyqan ",
    // span: "Zgjidh Dyqanin {\">\"}",
    span: "Zgjidh Dyqanin",
    shporta: "Shto ne shporte"
},
{
    id: 2,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    img: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320" ,
    llojiPaisjes: "Lloji i pajisjes:",
    paisja: "SMARTWATCH",
    sistemiOperativ: "Sisteme operative te pajtueshme:",
    sensori: "Sensori i rrahjeve te zemres:",
    sensoriInfo: "po",
    bateri: "Jetegjatesia e baterise:",
    bateriinfo: "288 ore",
    stars: "⭐⭐⭐⭐⭐",
    paragraphStars: "32",
    cmimiRekomandim: "E rekomanduar 39.99 €",
    cmimi: "34,99 €",
    link: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    kontributi: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    opsionetDorezimi: "Opsionet e dorezimit",
    opsionetDorezimi2: "+2,99 €",
    opsionetDorezimi3: " Dorezimi i parashikuar 21.08.2024 - 23.08.2024 (Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    koleksioni: "Koleksioni FALAS ne dyqan",
    kontrollKolkesioni: "Kontrolloni koleksionin ne dyqan ",
    // span: "Zgjidh Dyqanin {\">\"}",
    span: "Zgjidh Dyqanin",
    shporta: "Shto ne shporte"
},
{
    id: 3,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    img: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320" ,
    llojiPaisjes: "Lloji i pajisjes:",
    paisja: "SMARTWATCH",
    sistemiOperativ: "Sisteme operative te pajtueshme:",
    sensori: "Sensori i rrahjeve te zemres:",
    sensoriInfo: "po",
    bateri: "Jetegjatesia e baterise:",
    bateriinfo: "288 ore",
    stars: "⭐⭐⭐⭐⭐",
    paragraphStars: "32",
    cmimiRekomandim: "E rekomanduar 39.99 €",
    cmimi: "34,99 €",
    link: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    kontributi: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    opsionetDorezimi: "Opsionet e dorezimit",
    opsionetDorezimi2: "+2,99 €",
    opsionetDorezimi3: " Dorezimi i parashikuar 21.08.2024 - 23.08.2024 (Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    koleksioni: "Koleksioni FALAS ne dyqan",
    kontrollKolkesioni: "Kontrolloni koleksionin ne dyqan ",
    // span: "Zgjidh Dyqanin {\">\"}",
    span: "Zgjidh Dyqanin",
    shporta: "Shto ne shporte"
},
{
    id: 4,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    img: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320" ,
    llojiPaisjes: "Lloji i pajisjes:",
    paisja: "SMARTWATCH",
    sistemiOperativ: "Sisteme operative te pajtueshme:",
    sensori: "Sensori i rrahjeve te zemres:",
    sensoriInfo: "po",
    bateri: "Jetegjatesia e baterise:",
    bateriinfo: "288 ore",
    stars: "⭐⭐⭐⭐⭐",
    paragraphStars: "32",
    cmimiRekomandim: "E rekomanduar 39.99 €",
    cmimi: "34,99 €",
    link: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    kontributi: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    opsionetDorezimi: "Opsionet e dorezimit",
    opsionetDorezimi2: "+2,99 €",
    opsionetDorezimi3: " Dorezimi i parashikuar 21.08.2024 - 23.08.2024 (Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    koleksioni: "Koleksioni FALAS ne dyqan",
    kontrollKolkesioni: "Kontrolloni koleksionin ne dyqan ",
    // span: "Zgjidh Dyqanin {\">\"}",
    span: "Zgjidh Dyqanin",
    shporta: "Shto ne shporte"
},
{
    id: 5,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    img: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320" ,
    llojiPaisjes: "Lloji i pajisjes:",
    paisja: "SMARTWATCH",
    sistemiOperativ: "Sisteme operative te pajtueshme:",
    sensori: "Sensori i rrahjeve te zemres:",
    sensoriInfo: "po",
    bateri: "Jetegjatesia e baterise:",
    bateriinfo: "288 ore",
    stars: "⭐⭐⭐⭐⭐",
    paragraphStars: "32",
    cmimiRekomandim: "E rekomanduar 39.99 €",
    cmimi: "34,99 €",
    link: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    kontributi: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    opsionetDorezimi: "Opsionet e dorezimit",
    opsionetDorezimi2: "+2,99 €",
    opsionetDorezimi3: " Dorezimi i parashikuar 21.08.2024 - 23.08.2024 (Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    koleksioni: "Koleksioni FALAS ne dyqan",
    kontrollKolkesioni: "Kontrolloni koleksionin ne dyqan ",
    // span: "Zgjidh Dyqanin {\">\"}",
    span: "Zgjidh Dyqanin",
    shporta: "Shto ne shporte"
},
{
    id: 6,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    img: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320" ,
    llojiPaisjes: "Lloji i pajisjes:",
    paisja: "SMARTWATCH",
    sistemiOperativ: "Sisteme operative te pajtueshme:",
    sensori: "Sensori i rrahjeve te zemres:",
    sensoriInfo: "po",
    bateri: "Jetegjatesia e baterise:",
    bateriinfo: "288 ore",
    stars: "⭐⭐⭐⭐⭐",
    paragraphStars: "32",
    cmimiRekomandim: "E rekomanduar 39.99 €",
    cmimi: "34,99 €",
    link: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    kontributi: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    opsionetDorezimi: "Opsionet e dorezimit",
    opsionetDorezimi2: "+2,99 €",
    opsionetDorezimi3: " Dorezimi i parashikuar 21.08.2024 - 23.08.2024 (Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    koleksioni: "Koleksioni FALAS ne dyqan",
    kontrollKolkesioni: "Kontrolloni koleksionin ne dyqan ",
    // span: "Zgjidh Dyqanin {\">\"}",
    span: "Zgjidh Dyqanin",
    shporta: "Shto ne shporte"
},
{
    id: 7,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    img: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320" ,
    llojiPaisjes: "Lloji i pajisjes:",
    paisja: "SMARTWATCH",
    sistemiOperativ: "Sisteme operative te pajtueshme:",
    sensori: "Sensori i rrahjeve te zemres:",
    sensoriInfo: "po",
    bateri: "Jetegjatesia e baterise:",
    bateriinfo: "288 ore",
    stars: "⭐⭐⭐⭐⭐",
    paragraphStars: "32",
    cmimiRekomandim: "E rekomanduar 39.99 €",
    cmimi: "34,99 €",
    link: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    kontributi: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    opsionetDorezimi: "Opsionet e dorezimit",
    opsionetDorezimi2: "+2,99 €",
    opsionetDorezimi3: " Dorezimi i parashikuar 21.08.2024 - 23.08.2024 (Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    koleksioni: "Koleksioni FALAS ne dyqan",
    kontrollKolkesioni: "Kontrolloni koleksionin ne dyqan ",
    // span: "Zgjidh Dyqanin {\">\"}",
    span: "Zgjidh Dyqanin",
    shporta: "Shto ne shporte"
},
{
    id: 8,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    img: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320" ,
    llojiPaisjes: "Lloji i pajisjes:",
    paisja: "SMARTWATCH",
    sistemiOperativ: "Sisteme operative te pajtueshme:",
    sensori: "Sensori i rrahjeve te zemres:",
    sensoriInfo: "po",
    bateri: "Jetegjatesia e baterise:",
    bateriinfo: "288 ore",
    stars: "⭐⭐⭐⭐⭐",
    paragraphStars: "32",
    cmimiRekomandim: "E rekomanduar 39.99 €",
    cmimi: "34,99 €",
    link: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    kontributi: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    opsionetDorezimi: "Opsionet e dorezimit",
    opsionetDorezimi2: "+2,99 €",
    opsionetDorezimi3: " Dorezimi i parashikuar 21.08.2024 - 23.08.2024 (Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    koleksioni: "Koleksioni FALAS ne dyqan",
    kontrollKolkesioni: "Kontrolloni koleksionin ne dyqan ",
    // span: "Zgjidh Dyqanin {\">\"}",
    span: "Zgjidh Dyqanin",
    shporta: "Shto ne shporte"
},

]
export default CardData;